services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/humphrey.egg-info
    image: ghcr.io/williamjacksn/humphrey-dev
    init: true
    volumes:
      - ./:/home/python/humphrey
    working_dir: /home/python/humphrey

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/humphrey-dev
    init: true
    volumes:
      - ./:/home/python/humphrey
    working_dir: /home/python/humphrey

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/humphrey-dev
    init: true
    volumes:
      - ./:/home/python/humphrey
    working_dir: /home/python/humphrey
