name: Build the helper image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

env:
  image_name: ghcr.io/williamjacksn/humphrey-dev

jobs:
  build:
    name: Build the helper image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ github.token }}
          username: ${{ github.actor }}

      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.image_name }}

      - name: Push latest image to registry
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.image_name }}:latest
